import {ProductType} from './ProductType';
import {ReviewType} from './ReviewType';

export type RootStackParamList = {
  FAQ: undefined;
  Filter: undefined;
  SignIn: undefined;
  SignUp: undefined;
  Checkout: undefined;
  MyAddress: undefined;
  Onboarding: undefined;
  EditProfile: undefined;
  NewPassword: undefined;
  OrderFailed: undefined;
  AddANewCard: undefined;
  OrderHistory: undefined;
  LeaveAReview: undefined;
  MyPromocodes: undefined;
  TabNavigator: undefined;
  Notifications: undefined;
  LeaveAReviews: undefined;
  PaymentMethod: undefined;
  ForgotPassword: undefined;
  TrackYourOrder: undefined;
  AddANewAddress: undefined;
  OrderSuccessful: undefined;
  ConfirmationCode: undefined;
  Product: {item: ProductType};
  MyPromocodesEmpty: undefined;
  SignUpAccountCreated: undefined;
  VerifyYourPhoneNumber: undefined;
  Reviews: {reviews: ReviewType[]};
  Description: {description: string};
  ForgotPasswordSentEmail: undefined;
  Shop: {products?: ProductType[]; title?: string} | undefined;
};
